from app.models import db, Person


def seed_people():
    seedArray = []

    seedArray.append(Person(numeric_identifier=100, first_name="Fiona", last_name="Miller", zone_id=1))
    seedArray.append(Person(numeric_identifier=101, first_name="Byron", last_name="Gray", zone_id=1))
    seedArray.append(Person(numeric_identifier=102, first_name="Robert", last_name="Owens", zone_id=1))
    seedArray.append(Person(numeric_identifier=103, first_name="Julia", last_name="Wright", zone_id=1))
    seedArray.append(Person(numeric_identifier=104, first_name="Sam", last_name="Hill", zone_id=1))
    seedArray.append(Person(numeric_identifier=105, first_name="Connie", last_name="Lloyd", zone_id=1))
    seedArray.append(Person(numeric_identifier=106, first_name="Edgar", last_name="Stevens", zone_id=1))
    seedArray.append(Person(numeric_identifier=107, first_name="Agata", last_name="Morris", zone_id=1))
    seedArray.append(Person(numeric_identifier=108, first_name="Kristian", last_name="Murray", zone_id=1))
    seedArray.append(Person(numeric_identifier=109, first_name="Alan", last_name="Hill", zone_id=1))
    seedArray.append(Person(numeric_identifier=110, first_name="Mike", last_name="Harper", zone_id=1))
    seedArray.append(Person(numeric_identifier=111, first_name="Ellia", last_name="Armstrong", zone_id=1))
    seedArray.append(Person(numeric_identifier=112, first_name="Brianna", last_name="Barrett", zone_id=1))
    seedArray.append(Person(numeric_identifier=113, first_name="Lydia", last_name="Lloyd", zone_id=1))
    seedArray.append(Person(numeric_identifier=114, first_name="Martin", last_name="Mason", zone_id=1))
    seedArray.append(Person(numeric_identifier=115, first_name="Savana", last_name="Ferguson", zone_id=1))
    seedArray.append(Person(numeric_identifier=116, first_name="Edgar", last_name="Morrison", zone_id=1))
    seedArray.append(Person(numeric_identifier=117, first_name="Eddy", last_name="Cunningham", zone_id=1))
    seedArray.append(Person(numeric_identifier=201, first_name="William", last_name="West", zone_id=2))
    seedArray.append(Person(numeric_identifier=202, first_name="Catherine", last_name="Carroll", zone_id=2))
    seedArray.append(Person(numeric_identifier=203, first_name="Ashton", last_name="Evans", zone_id=2))
    seedArray.append(Person(numeric_identifier=204, first_name="Vivian", last_name="Perry", zone_id=2))
    seedArray.append(Person(numeric_identifier=205, first_name="Naomi", last_name="Warren", zone_id=2))
    seedArray.append(Person(numeric_identifier=206, first_name="Rosie", last_name="Perry", zone_id=2))
    seedArray.append(Person(numeric_identifier=207, first_name="Sam", last_name="Stevens", zone_id=2))
    seedArray.append(Person(numeric_identifier=208, first_name="Kimberly", last_name="Roberts", zone_id=2))
    seedArray.append(Person(numeric_identifier=209, first_name="Patrick", last_name="Thomas", zone_id=2))
    seedArray.append(Person(numeric_identifier=210, first_name="Nicole", last_name="Myers", zone_id=2))
    seedArray.append(Person(numeric_identifier=211, first_name="Victoria", last_name="Clark", zone_id=2))
    seedArray.append(Person(numeric_identifier=212, first_name="Grace", last_name="Carter", zone_id=2))
    seedArray.append(Person(numeric_identifier=213, first_name="Miller", last_name="Johnston", zone_id=2))
    seedArray.append(Person(numeric_identifier=214, first_name="Belinda", last_name="Harper", zone_id=2))
    seedArray.append(Person(numeric_identifier=215, first_name="Adam", last_name="Hawkins", zone_id=2))
    seedArray.append(Person(numeric_identifier=216, first_name="Hailey", last_name="Cooper", zone_id=2))
    seedArray.append(Person(numeric_identifier=301, first_name="Miley", last_name="Tucker", zone_id=3))
    seedArray.append(Person(numeric_identifier=302, first_name="Ryan", last_name="Campbell", zone_id=3))
    seedArray.append(Person(numeric_identifier=303, first_name="Connie", last_name="West", zone_id=3))
    seedArray.append(Person(numeric_identifier=304, first_name="Amanda", last_name="Stevens", zone_id=3))
    seedArray.append(Person(numeric_identifier=305, first_name="Edward", last_name="Casey", zone_id=3))
    seedArray.append(Person(numeric_identifier=306, first_name="Vincent", last_name="West", zone_id=3))
    seedArray.append(Person(numeric_identifier=307, first_name="Robert", last_name="Foster", zone_id=3))
    seedArray.append(Person(numeric_identifier=308, first_name="Dainton", last_name="Grant", zone_id=3))
    seedArray.append(Person(numeric_identifier=309, first_name="Kirsten", last_name="Gray", zone_id=3))
    seedArray.append(Person(numeric_identifier=310, first_name="Adam", last_name="Ryan", zone_id=3))
    seedArray.append(Person(numeric_identifier=311, first_name="Kelsey", last_name="West", zone_id=3))
    seedArray.append(Person(numeric_identifier=312, first_name="Aiden", last_name="Johnson", zone_id=3))
    seedArray.append(Person(numeric_identifier=313, first_name="Natalie", last_name="Murphy", zone_id=3))
    seedArray.append(Person(numeric_identifier=314, first_name="Ted", last_name="Smith", zone_id=3))
    seedArray.append(Person(numeric_identifier=315, first_name="Sydney", last_name="Wright", zone_id=3))
    seedArray.append(Person(numeric_identifier=316, first_name="Cherry", last_name="Hunt", zone_id=3))
    seedArray.append(Person(numeric_identifier=317, first_name="Chloe", last_name="Richardson", zone_id=3))
    seedArray.append(Person(numeric_identifier=318, first_name="Jack", last_name="Ferguson", zone_id=3))
    seedArray.append(Person(numeric_identifier=319, first_name="Jared", last_name="Warren", zone_id=3))
    seedArray.append(Person(numeric_identifier=320, first_name="Samantha", last_name="Perry", zone_id=3))
    seedArray.append(Person(numeric_identifier=321, first_name="Thomas", last_name="Craig", zone_id=3))
    seedArray.append(Person(numeric_identifier=401, first_name="Spike", last_name="Perkins", zone_id=4))
    seedArray.append(Person(numeric_identifier=402, first_name="Olivia", last_name="Higgins", zone_id=4))
    seedArray.append(Person(numeric_identifier=403, first_name="Lyndon", last_name="Davis", zone_id=4))
    seedArray.append(Person(numeric_identifier=404, first_name="John", last_name="Henderson", zone_id=4))
    seedArray.append(Person(numeric_identifier=405, first_name="Tiana", last_name="Bennett", zone_id=4))
    seedArray.append(Person(numeric_identifier=406, first_name="Fiona", last_name="Allen", zone_id=4))
    seedArray.append(Person(numeric_identifier=407, first_name="Jared", last_name="Walker", zone_id=4))
    seedArray.append(Person(numeric_identifier=408, first_name="Miley", last_name="Perry", zone_id=4))
    seedArray.append(Person(numeric_identifier=409, first_name="Lucas", last_name="Crawford", zone_id=4))
    seedArray.append(Person(numeric_identifier=410, first_name="Sabrina", last_name="Richardson", zone_id=4))
    seedArray.append(Person(numeric_identifier=411, first_name="Michael", last_name="Myers", zone_id=4))
    seedArray.append(Person(numeric_identifier=412, first_name="Belinda", last_name="Sullivan", zone_id=4))
    seedArray.append(Person(numeric_identifier=413, first_name="Jared", last_name="Watson", zone_id=4))
    seedArray.append(Person(numeric_identifier=414, first_name="Roman", last_name="Grant", zone_id=4))
    seedArray.append(Person(numeric_identifier=415, first_name="Briony", last_name="Walker", zone_id=4))
    seedArray.append(Person(numeric_identifier=416, first_name="Evelyn", last_name="Martin", zone_id=4))
    seedArray.append(Person(numeric_identifier=417, first_name="Clark", last_name="Anderson", zone_id=4))
    seedArray.append(Person(numeric_identifier=418, first_name="Abraham", last_name="Crawford", zone_id=4))
    seedArray.append(Person(numeric_identifier=419, first_name="Sofia", last_name="Ferguson", zone_id=4))






    for item in seedArray:
        db.session.add(item)

    db.session.commit()