"""empty message

Revision ID: e627576d9cb7
Revises: 1dee03e49c9b
Create Date: 2021-10-28 22:53:57.817834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e627576d9cb7'
down_revision = '1dee03e49c9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('numeric_identifier', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'numeric_identifier')
    # ### end Alembic commands ###
